App/models/user.py
from werkzeug.security import check_password_hash, generate_password_hash
from App.database import db

class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username =  db.Column(db.String, nullable=False, unique=True)
    password = db.Column(db.String(120), nullable=False)

    def __init__(self, username, password):
        self.username = username
        self.set_password(password)

    def get_json(self):
        return{
            'id': self.id,
            'username': self.username
        }

    def set_password(self, password):
        """Create hashed password."""
        self.password = generate_password_hash(password)
    
    def check_password(self, password):
        """Check hashed password."""
        return check_password_hash(self.password, password)

App/controllers/user.py
from App.models import User
from App.database import db

def create_user(username, password):
    newuser = User(username=username, password=password)
    db.session.add(newuser)
    db.session.commit()
    return newuser

def get_user_by_username(username):
    return User.query.filter_by(username=username).first()

def get_user(id):
    return User.query.get(id)

def get_all_users():
    return User.query.all()

def get_all_users_json():
    users = User.query.all()
    if not users:
        return []
    users = [user.get_json() for user in users]
    return users

def update_user(id, username):
    user = get_user(id)
    if user:
        user.username = username
        db.session.add(user)
        return db.session.commit()
    return None
    

App/views/auth.py
from flask import Blueprint, render_template, jsonify, request, flash, send_from_directory, flash, redirect, url_for
from flask_jwt_extended import jwt_required, current_user, unset_jwt_cookies, set_access_cookies, get_jwt_identity
from werkzeug.security import generate_password_hash
from werkzeug.urls import url_parse
from sqlalchemy import or_
from App.models import db
from App.database import db

from App.controllers import (
    login, signup
)

from App.models import (
    Workout,
    Routine,
    RoutineWorkout,
    User
)

auth_views = Blueprint('auth_views', __name__, template_folder='../templates')


'''
Page/Action Routes
'''
@auth_views.route('/index', methods=['GET'])
def index_page():
    return render_template('index.html')

@auth_views.route('/users', methods=['GET'])
def get_user_page():
    users = get_all_users()
    return render_template('users.html', users=users)

@auth_views.route('/identify', methods=['GET'])
@jwt_required()
def identify_page():
    return render_template('message.html', title="Identify", message=f"You are logged in as {current_user.id} - {current_user.username}")

@auth_views.route('/signup', methods=['GET'])
def signup_page():
    return render_template('signup.html')
 
@auth_views.route('/signup', methods=['POST'])
def signup_action():
    username = request.form.get('new_username')  
    password = request.form.get('new_password') 

    # Check if username already exists
    existing_user = User.query.filter_by(username=username).first()
    if existing_user:
        flash('Username already exists. Please choose a different one.', 'error')
        return redirect(request.referrer or url_for('auth_views.signup_page')) # this line will force the redirect to x instead of the 401 page

    # Create new user
    #hashed_password = generate_password_hash(password)
    #new_user = User(username=username, password=hashed_password)
    new_user = User(username=username, password=password)
    db.session.add(new_user)
    db.session.commit()

    # Log in the new user
    token = login(username, password)
    if not token:
        flash('Failed to log in after signup.', 'error')
        return redirect(url_for('auth_views.home_page'))

    # Redirect to home page
    response = redirect(url_for('auth_views.home_page'))
    flash('Signup successful. Welcome!', 'success')
    set_access_cookies(response, token)
    return response

@auth_views.route('/login', methods=['POST'])
def login_action():
    data = request.form
    token = login(data['username'], data['password'])
    response = redirect(url_for('auth_views.home_page'))
    #response = redirect(request.referrer)
    if not token:
        flash('Bad username or password given'), 401
    else:
        flash('Login Successful')
        set_access_cookies(response, token) 
    return response


@auth_views.route('/home', methods=['GET', 'POST'])
@jwt_required()
def home_page():
    search_query = request.args.get('search', default='', type=str)
    workouts = None
    selected_workout = None
    user_routines = Routine.query.filter_by(user_id=current_user.id).all()
    selected_routine = None

    if request.method == 'POST':
        if 'delete_routine' in request.form:
            routine_id = request.form.get('routine_id')
            RoutineWorkout.query.filter_by(routine_id=routine_id).delete()
            db.session.commit()
            Routine.query.filter_by(id=routine_id).delete()
            db.session.commit()
            flash('Routine deleted successfully.', 'success')
            return redirect(url_for('auth_views.home_page'))

        if 'delete_workout_from_routine' in request.form:
            routine_workout_id = request.form.get('routine_workout_id')
            RoutineWorkout.query.filter_by(id=routine_workout_id).delete()
            db.session.commit()
            flash('Workout removed from routine successfully.', 'success')
            return redirect(request.referrer or url_for('auth_views.home_page'))

        if 'routine_workout_id' in request.form and request.form.get('action') == 'update':
            routine_workout_id = request.form.get('routine_workout_id', type=int)
            reps = request.form.get('reps', type=int)
            sets = request.form.get('sets', type=int)
            # Validate input
            if reps is not None and sets is not None and routine_workout_id is not None:
                routine_workout = RoutineWorkout.query.get(routine_workout_id)
                if routine_workout:
                    routine_workout.reps = reps
                    routine_workout.sets = sets
                    db.session.commit()
                    flash('Workout updated successfully.', 'success')
                else:
                    flash('Could not find the specified workout in the routine.', 'error')
            else:
                flash('Invalid input for updating workout.', 'error')
            return redirect(request.referrer or url_for('auth_views.home_page'))

        routine_id = request.form.get('routine_id')
        if 'workout_id' in request.form:
            workout_id = request.form.get('workout_id')
            reps = request.form.get('reps', type=int)
            sets = request.form.get('sets', type=int)
            #print(f"routine_id: {routine_id}, reps: {reps}, sets: {sets}.")

            if not reps or not sets or not routine_id:
                flash('Please ensure all fields are filled out correctly. Reps and Sets must be above 0, and a Routine must be selected.', 'error')
                return redirect(request.referrer or url_for('auth_views.home_page', workout_id=workout_id))
            else:
                if RoutineWorkout.query.filter_by(routine_id=routine_id, workout_id=workout_id).first():
                    flash('Workout already exists in this routine.', 'warning')
                else:
                    routine_workout = RoutineWorkout(routine_id=routine_id, workout_id=workout_id, reps=reps, sets=sets)
                    db.session.add(routine_workout)
                    db.session.commit()
                    flash('Workout added to routine successfully.', 'success')
            return redirect(request.referrer or url_for('auth_views.home_page'))

        elif 'routine_title' in request.form:
            # Handle creating routine
            routine_title = request.form.get('routine_title')
            # Ensures a user enters 1 or more character(s) for routine title
            if not routine_title:
                flash('Routine title is required.', 'danger')
                return redirect(request.referrer or url_for('auth_views.home_page'))
            existing_routine = Routine.query.filter_by(title=routine_title, user_id=current_user.id).first()
            if existing_routine:
                flash('Routine with the same title already exists.', 'danger')
            else:
                new_routine = Routine(title=routine_title, user_id=current_user.id)
                db.session.add(new_routine)
                db.session.commit()
                flash('Routine created successfully.', 'success')
            return redirect(request.referrer or url_for('auth_views.home_page'))

    if search_query:
        workouts = Workout.query.filter(Workout.title.ilike(f'%{search_query}%')).all()
        if not workouts:
            flash('No workouts found for the search query.', 'warning')
    else:
        workout_id = request.args.get('workout_id', type=int)
        if workout_id:
            selected_workout = Workout.query.get_or_404(workout_id)
        workouts = Workout.query.all()

    routine_id = request.args.get('routine_id', type=int)
    
    if routine_id:
        selected_routine = Routine.query.get_or_404(routine_id)

    return render_template('home.html', workouts=workouts, selected_workout=selected_workout, user_routines=user_routines, selected_routine=selected_routine, is_authenticated=True)



@auth_views.route('/logout', methods=['GET'])
@jwt_required()
def logout_action():
    response = redirect(url_for('auth_views.index_page'))
    flash("Logged Out!")
    unset_jwt_cookies(response)
    return response

'''
API Routes
'''

@auth_views.route('/api/login', methods=['POST'])
def user_login_api():
  data = request.json
  token = login(data['username'], data['password'])
  if not token:
    return jsonify(message='bad username or password given'), 401
  response = jsonify(access_token=token) 
  set_access_cookies(response, token)
  return response

@auth_views.route('/api/identify', methods=['GET'])
@jwt_required()
def identify_user():
    return jsonify({'message': f"username: {current_user.username}, id : {current_user.id}"})

@auth_views.route('/api/logout', methods=['GET'])
@jwt_required()
def logout_api():
    response = jsonify(message="Logged Out!")
    unset_jwt_cookies(response)
    return response

@auth_views.route('/', defaults={'path': ''})
@auth_views.route('/<path:path>')
def catch_all(path):
    return redirect(url_for('auth_views.home_page'))

App/views/user.py
from flask import Blueprint, render_template, jsonify, request, send_from_directory, flash, redirect, url_for
from flask_jwt_extended import jwt_required, current_user as jwt_current_user

from.index import index_views

from App.controllers import (
    create_user,
    get_all_users,
    get_all_users_json,
    jwt_required
)

user_views = Blueprint('user_views', __name__, template_folder='../templates')

@user_views.route('/users', methods=['GET'])
def get_user_page():
    users = get_all_users()
    return render_template('users.html', users=users)

@user_views.route('/users', methods=['POST'])
def create_user_action():
    data = request.form
    flash(f"User {data['username']} created!")
    create_user(data['username'], data['password'])
    return redirect(url_for('user_views.get_user_page'))

@user_views.route('/api/users', methods=['GET'])
def get_users_action():
    users = get_all_users_json()
    return jsonify(users)

@user_views.route('/api/users', methods=['POST'])
def create_user_endpoint():
    data = request.json
    user = create_user(data['username'], data['password'])
    return jsonify({'message': f"user {user.username} created with id {user.id}"})

@user_views.route('/static/users', methods=['GET'])
def static_user_page():
  return send_from_directory('static', 'static-user.html')

App/templates/401.html
{% extends "layout.html" %}
{% block title %}Not Authorized{% endblock %}
{% block page %}<img src="static/logo4.png" alt="gymrat" style="width: 8vw; height: 7vh;"> {% endblock %}

{{ super() }}

{% block content %}
<div class="container">
    <div class="row" style="margin-top: 10%;">
        <div class="col s12 m10 offset-m1">
            <div class="card-content">
                <h1>401 - Not Authorized</h1>
                <p>You do not have permission to access this resource. Please check your credentials and try again.</p>
                <p>{{error}}</p>
            </div>
            <div class="card-action">
                <a href="/" class="waves-effect waves-light btn">Go Home</a>
                <a href="javascript:history.back()" class="waves-effect waves-light btn">Go Back</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

App/templates/home.html
{% extends "layout.html" %}
{% block title %}Home{% endblock %}
{% block page %}{% endblock %}

{% block styles %}
<style>
.left-align {
    margin: 0;
    padding: 0;
}

</style>

{% endblock %}

{% block content %}


<div class="row">
    {% if is_authenticated %}
    <div class="row">
        <!-- Left section: Search bar and list of workouts -->
        <div class="col s12 m6 l3" style="max-height: 92vh;  overflow-y: scroll; background-color:#494d5c;  border-radius: 20px; padding:30px;">
            <h5 class="header-text">Workouts</h5>
            <div class="collection">
                {% if workouts %}
                    {% for workout in workouts %}
                    <a href="/home?workout_id={{ workout.id }}{% if selected_routine %}&routine_id={{ selected_routine.id }}{% endif %}" class="collection-item {% if selected_workout and selected_workout.id == workout.id %}active white-text{% else %}black-text{% endif %}">{{ workout.title }}</a>
                    {% endfor %}
                {% endif %}
            </div>
        </div>


        <!-- Middle section: Selected workout details -->
      
        <!-- background-color: #373d4e; -->
      <div class="col s12 m6 l3" style="height: 92vh; background-color: #292d3a; border-radius: 20px; color:white; font-family: 'Tahoma', Geneva, Verdana, sans-serif;
      text-align: center; font-size: large; padding:30px;">  
            <h5 class="header-text">Selected Workout:</h5>
            {% if selected_workout %}
                <h4>{{ selected_workout.title }}</h4>
                {% if selected_workout.description %}
                    <p>{{ selected_workout.description }}</p>  <!-- This will hide the empty description boxes -->
                {% endif %}
                <!-- <p>{{ selected_workout.description }}</p> -->
                <p>Type: {{ selected_workout.type }}</p>
                <p>Body Part: {{ selected_workout.body_part }}</p>
                <p>Equipment: {{ selected_workout.equipment }}</p>
                <p>Level: {{ selected_workout.level }}</p>
                <!-- Add other workout details here -->
                <form action="/home" method="POST">
                    <div style="background-color: rgb(255, 255, 255); border-radius: 10px; justify-content: center; align-items: center; padding: 20px;
                    font-family: 'Baskerville', Tahoma, Geneva, Verdana, sans-serif;"> 
                    <input type="hidden" style="width:50%;" name="workout_id" value="{{ selected_workout.id }}">
                    <label for="reps">Reps:</label>
                    <input type="number" id="reps" name="reps" value="0" min="0">
                    <label for="sets">Sets:</label>
                    <input type="number" id="sets" name="sets" value="0" min="0">
                    <select name="routine_id">
                        <option value="" disabled selected>Select Routine</option>
                        {% for routine in user_routines %}
                            <option value="{{ routine.id }}">{{ routine.title }}</option>
                        {% endfor %}
                    </select>
                    <button class="green-button" type="submit">Add to Routine</button>
                    </div>
                </form>
            {% endif %}
        </div>


        <!-- SELECTED_ROUTINE -->
        <div class="col s12 m6 l3" style="height: 92vh; background-color: #292d3a; border-radius: 20px; font-family: 'Tahoma', Geneva, Verdana, sans-serif;
        text-align: center; font-size: large; padding:30px;">   
            <h5 class="header-text">Selected Routine:</h5>
            {% if selected_routine %}
                <h4 style="color:white">{{selected_routine.title}}</h4> 

               <!-- <div style="background-color: rgb(255, 255, 255); border-radius: 20px; justify-content: center; align-items: center; padding: 5px;
                    font-family: 'Baskerville', Tahoma, Geneva, Verdana, sans-serif;"> -->

                    <div>
                        <ul class="collapsible" data-collapsible="accordion" style="background-color: white; border-radius: 10px;">
                            {% for routine_workout in selected_routine.routine_workouts %}
                            <li>

                                <!-- add an active class tag? -->
                                <div class="collapsible-header no-shadow" style="background-color: white; border-radius: 10px;">{{ routine_workout.workout.title }}</div>
                                <div class="collapsible-body no-shadow"style="background-color: white; border-radius: 10px;">
                                    <form action="/home" method="POST">

                                        <input type="hidden" name="routine_workout_id" value="{{ routine_workout.id }}">

                                        <label for="reps">Reps:</label>
                                        <input type="number" id="reps" name="reps" value="{{ routine_workout.reps }}"
                                            min="0">
                                        <label for="sets">Sets:</label>
                                        <input type="number" id="sets" name="sets" value="{{ routine_workout.sets }}"
                                            min="0">
                                        <input type="hidden" name="action" value="update"> <!-- Add this hidden input -->
                                        <button class="green-button" type="submit">Update</button>
                                    </form>
                                    <br>
                                    <form action="/home" method="POST">
                                        <input type="hidden" name="routine_workout_id" value="{{ routine_workout.id }}" />
                                        <button type="submit" class="red-button" name="delete_workout_from_routine"
                                            value="true">Delete</button>
                                    </form>
                                </div>
                            </li>
                            {% endfor %}
                        </ul>
                </div>        
                   
                <div style="margin-top:30px;">
                <form action="/home" method="POST" style="display:inline;">
                    <input type="hidden" name="routine_id" value="{{ selected_routine.id }}">
                    <button type="submit" class="red-button" name="delete_routine" value="true">Delete Entire Routine</button>
                </form>
                </div>
        {% endif %}
        </div>


        <!-- Right section: User routines CREATION and management -->
        <div class="col s12 m6 l3" style="height:92vh; background-color: #494d5c;  border-radius: 20px; display:flex; flex-direction: column; padding:30px;" >

            
            <h5 class="header-text">Create Routine</h5>
            
            <div style="padding:30px;">
            <form action="/home" method="POST">
                <div class="input-field">
                    <input id="routine_title" style="text-align: center; color:white;" name="routine_title" type="text" placeholder="Routine Title">
                    <label for="routine_title"></label>
                </div>

                <div style="align-items:center; justify-content: center; display:flex; flex-direction: column;"><button class="green-button" type="submit">Create Routine</button></div>
                
                

            </form>
            </div>


            <h5 class="header-text" style="margin-top: 5vh;">Your Routines</h5>
                 <div> 
                    {% if user_routines %}
                    <div style="margin-top: 2vh;">
                    <ul class="collection" style="background-color: white; border-radius: 10px;">
                        <div class="collection-list" style="background-color: white; border-radius: 10px;"> 
                                {% for routine in user_routines %}
                                <a href="/home?routine_id={{ routine.id }}{% if selected_workout %}&workout_id={{ selected_workout.id }}{% endif %}" class="collection-item {% if selected_routine and selected_routine.id == routine.id %}active white-text{% else %}black-text{% endif %}">{{ routine.title }}</a>
                                {% endfor %}
                        </div>
                    </ul>
                    {% else %}
                        <p style="color:white;">No routines found. Create a routine to get started.</p>
                    </div>
                    {% endif %}
                </div>
    </div>
    {% else %}
    <div class="row">
        <div class="col s12">
            <h5>Please login to view this page.</h5>
        </div>
    </div>
    {% endif %}
</div>


<script>
    function toggleCollapse(element) {
        var collapsible = element.closest('li').querySelector('.collapsible');
        if (collapsible.style.display === "none") {
            collapsible.style.display = "block";
        } else {
            collapsible.style.display = "none";
        }
    }
</script>
{% endblock %}

App/templates/index.html
<!doctype html>
<html>
  <head>

    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
     <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>{% block title %}GYM RAT{% endblock %}</title>

  </head>
  <body>

{% block styles %}
    <style>

         body {
            background-color: black;
            margin: 0; 
        }

            .background-container {

            background-image: url('static/page-back.jpg');
            background-size: cover;
            background-position: center;
            height: 97vh; 
            width: 100vw;
            background-attachment: fixed; 
            margin: 0;
            padding: 0; 
        }

        .login-link {
  align-items: center;
  /*background-image: linear-gradient(144deg,#AF40FF, #5B42F3 50%,#00DDEB);*/
  background-image: linear-gradient(144deg, #f07832,
     #f5b506 50%,
     #f09929,
     #d13c01);
  border: 0;
  border-radius: 8px;
  box-shadow: rgba(151, 65, 252, 0.2) 0 15px 30px -5px;
  box-sizing: border-box;
  color: #000000;
  display: flex;
  font-family: Phantomsans, sans-serif;
  justify-content: center;
  line-height: 1em;
  max-width: 100%;
  min-width: 5vw;
  padding: 10px;
  text-decoration: none;
  user-select: none;
  -webkit-user-select: none;
  touch-action: manipulation;
  white-space: nowrap;
  cursor: pointer;
}

.login-link:active,
.login-link:hover {
  outline: 0;
}

.login-link span {
  background-color: rgb(5, 6, 45);
  padding: 16px 24px;
  border-radius: 6px;
  width: 100%;
  height: 100%;
  transition: 300ms;
}

.login-link:hover span {
  background: none;
}

@media (min-width: 768px) {
  .login-link {
    font-size: 20px;
    padding:10px;
  }
}

.auth-link {
  font-family: Phantomsans, sans-serif;
  padding: 0.6em 2em;
  border: none;
  outline: none;
  color: rgb(255, 255, 255);
  background: #111;
  cursor: pointer;
  position: relative;
  z-index: 0;
  border-radius: 10px;
  user-select: none;
  -webkit-user-select: none;
  touch-action: manipulation;
}

.auth-link:before {
  content: "";
  background: linear-gradient(
    45deg,
    #f07832,
     #d10909 50%,
     #e0f001,
     #f5024b

  );
  position: absolute;
  top: -2px;
  left: -2px;
  background-size: 400%;
  z-index: -1;
  filter: blur(5px);
  -webkit-filter: blur(5px);
  width: calc(100% + 4px);
  height: calc(100% + 4px);
  animation: glowing-button-85 20s linear infinite;
  transition: opacity 0.3s ease-in-out;
  border-radius: 10px;
}

@keyframes glowing-button-85 {
  0% {
    background-position: 0 0;
  }
  50% {
    background-position: 400% 0;
  }
  100% {
    background-position: 0 0;
  }
}

.auth-link:after {
  z-index: -1;
  content: "";
  position: absolute;
  width: 100%;
  height: 100%;
  background: #222;
  left: 0;
  top: 0;
  border-radius: 10px;
}

    </style>
{% endblock %}


{% block content %}

    <div class="background-container">


        <div class="row">

           <!-- header slogan -->
            <div class="col s12 grey-text" style="text-align: center; background-color: black;">Fitness, on your schedule.</div>

           <!-- Let us help you achieve... text-->
            <div class="col s6 white-text" style="background-color: rgba(0, 0, 0, 0.8); height: 97vh;" >

              <img src="static/letushelp.png" style="position: absolute; top: 50%; transform: translateY(-50%); width:45%;">
              
            
            


            </div>

            <!-- GYMRAT word logo -->
            <div class="col s6" style="height:97vh;">

                <div style="align-items: center; justify-content: center; display:flex;">


                  <!-- <div class="container"> -->
                    <div style="display: block; justify-content: center; align-items: center; height: 50vh; background-color: rgba(0, 0, 0, 0.9); margin-top: 15vh;"> 
                      <img class="responsive-img" src="static/logo4.png" >
                      <form method="POST" action="/login" style="align-items: center; justify-content:center; background-color: black; padding: 4vh;"> 
                        <div class="row">
                          <div class="input-field col s12">
                            <input placeholder="Username" value="" name="username" type="text" class="validate" required style="color: white;">
                            <!-- <label for="username">username</label> -->
                          </div>
                        </div>
                        <div class="row">
                          <div class="input-field col s12">
                            <input placeholder="Password" value="" name="password" type="password" class="validate" required style="color: white;">
                            <!-- <label for="password">Password</label> -->
                          </div>
                        </div>

                      <div style="display:flex;"> 
                        

                          <button type="submit" class="login-link" style="margin-left:0.5vw;">Login</button>

                          <button style="margin-left: 2vw;" class="auth-link"><a href="/signup" style="color: white; text-decoration: none;">Sign Up</a></button>


                      </div>
                  
                  </div>

              </div>



            </div>






    </div>

{% endblock %}

App/templates/message.html
{% extends "layout.html" %}
{% block title %}{{title}}{% endblock %}
{% block page %}<img src="static/logo4.png" alt="gymrat" style="width: 8vw; height: 7vh;"> {% endblock %}

{{ super() }}

{% block content %}
<div class="container">
    <div class="row" style="margin-top: 10%;">
        <div class="col s12 m10 offset-m1">
            <p>{{message}}</p>
        </div>
    </div>
</div>
{% endblock %}

App/templates/signup.html
{% extends "layout.html" %}
{% block title %}Signup{% endblock %}
{% block page %}{% endblock %}

{% block content %}
<div class="container" style="display: flex; justify-content: center; height: 100vh; padding-top:10vh;">
    <div style="width: 30vw;">
        <h3 style="color: white; text-align: center; margin-bottom: 5vh;">Account Creation</h3>

        <form action="{{ url_for('auth_views.signup_action') }}" method="POST">
            <div class="input-field">
                <input type="text" id="new_username" name="new_username" required style="color: white; border-radius: 15px;">
                <label for="username">Username</label>
            </div>
            <div class="input-field">
                <input type="password" id="new_password" name="new_password" required style="color: white; border-radius: 15px;">
                <label for="password">Password</label>
            </div>
            <div style="align-items:center; justify-content: center; display:flex; flex-direction: column;"><button class="green-button" type="submit">Sign Up</button></div>
        </form>
    </div>
</div>
{% endblock %}

App/templates/users.html
{% extends "layout.html" %}
{% block title %}App Users{% endblock %}
{% block page %}<img src="static/logo4.png" alt="gymrat" style="width: 8vw; height: 7vh;"> {% endblock %}

{{ super() }}

{% block content %}
    <div class="row">
        <p>
            This is table is renderd on the Server. Flask gets the data from the database and uses jinja templates to dyanmically render this page when a request is sent to <a href="/users">/users</a>.
        </p>
    </div>

    <div class="row">
      <form class="col s12" method="POST" action="/users">
        
        <div class="row">
          <div class="input-field col s6">
            <input placeholder="Username" name="username" type="text" class="validate">
            <label for="username">Username</label>
          </div>
          <div class="input-field col s6">
            <input placeholder="password" name="password" type="password" class="validate">
            <label for="password">Password</label>
          </div>
        </div>
      
        <div class="row">
          <div class="input-field col s12">
            <button class="btn waves-effect waves-light right purple" type="submit" name="action">Submit</button>
          </div>
        </div> 

      </form>
    </div>

    <div class="row">
      <table>
        <thead>
          <tr>
            <th>Id</th><th>Username</th>
          </tr>
        </thead>
        <tbody>
          {% for user in users %}
            <tr>
                <td>{{user.id}}</td>
                <td>{{user.username}}</td>
            </tr>
          {% endfor %}
        <tbody>
      </table>
    </div>

{% endblock %}